---

- name: Create certficates directory
  file:
    path: /etc/letsencrypt/live
    state: directory
    mode: 0600

- name: Generate letsencrypt certificates
  shell: certbot {{ letsencrypt_args }} --domains {{ item }} --pre-hook '{{ letsencrypt_pre_hook }}' --post-hook '{{ letsencrypt_post_hook }}'; echo "tst" > /etc/letsencrypt/live/{{ item }}
  args:
    creates: /etc/letsencrypt/live/{{ item }}/privkey.pem
  with_items: '{{ letsencrypt_domains }}'
  register: certificates_status

- debug:
    var: certificates_status

- name: Renew certificates crontab
  cron:
    name: "letsencrypt renew"
    minute: "0"
    hour: "6,16"
    job: certbot renew --pre-hook '{{ letsencrypt_renew_pre_hook }}' --post-hook '{{ letsencrypt_renew_post_hook }}'
    user: "root"
    state: "{{ letsencrypt_cron|ternary('present', 'absent') }}"
