---

- name: Create certficates directory
  file:
    path: /etc/letsencrypt/live
    state: directory
    mode: 0600

- name: Generate letsencrypt certificates
  shell: certbot {{ letsencrypt_args }} --domains {{ item }} --pre-hook "{{ _letsencrypt_pre_hooks | join(';') }}" --post-hook "{{ _letsencrypt_post_hooks | join(';') }}"; echo "tst" > /etc/letsencrypt/live/{{ item }}
  args:
    creates: /etc/letsencrypt/live/{{ item }}/privkey.pem
  with_items: '{{ letsencrypt_domains }}'
  register: certificates_status

- name: Renew certificates crontab
  cron:
    name: '{{ item.name | default(item) }}'
    minute: '{{ item.minute | default(omit) }}'
    hour: '{{ item.hour | default(omit) }}'
    job: certbot renew --pre-hook "{{ _letsencrypt_renew_pre_hooks | join(';') }}" --post-hook "{{ _letsencrypt_renew_post_hooks | join(';') }}"
    state: "{{ item.state | default(false) | ternary('present', 'absent') }}"
  with_items: '{{ letsencrypt_renew_cron }}'
